name: Docker build and push go-flux

on:
  push:
    paths:
      - "go-flux-video/**"

    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build-api-service:
    uses: dkr290/go-advanced-projects/.github/workflows/docker-build-template-noscan.yml@main
    with:
      name: Build and push go-flux image generator docker image
      docker_image_name: ghcr.io/${{ github.repository }}/go-flux-video
      version: "0.0.2"
      folder: go-flux-video
      dockerfileName: Dockerfile
